# Generated by Django 3.1.3 on 2023-02-24 16:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Title', max_length=100)),
                ('outcome', models.TextField(blank=True, default='outcome', max_length=256)),
                ('performance_goal_1', models.TextField(blank=True, default='Performance Goal', max_length=256)),
                ('performance_goal_2', models.TextField(blank=True, default='Performance Goal', max_length=256)),
                ('performance_goal_3', models.TextField(blank=True, default='Performance Goal', max_length=256)),
                ('process_goal_1', models.TextField(blank=True, default='Process Goal', max_length=256)),
                ('process_goal_2', models.TextField(blank=True, default='Process Goal', max_length=256)),
                ('process_goal_3', models.TextField(blank=True, default='Process Goal', max_length=256)),
                ('process_goal_4', models.TextField(blank=True, default='Process Goal', max_length=256)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlDiagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50)),
                ('can_control', models.BooleanField()),
                ('cannot_control', models.BooleanField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_control', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('cannot_control', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
