# Generated by Django 3.1.3 on 2021-01-24 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('performance_goal_1', models.CharField(blank=True, max_length=100)),
                ('performance_goal_2', models.CharField(blank=True, max_length=100)),
                ('performance_goal_3', models.CharField(blank=True, max_length=100)),
                ('process_goal_1', models.CharField(blank=True, max_length=100)),
                ('process_goal_2', models.CharField(blank=True, max_length=100)),
                ('process_goal_3', models.CharField(blank=True, max_length=100)),
                ('process_goal_4', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
