# Generated by Django 3.1.3 on 2021-01-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='outcome',
            field=models.CharField(blank=True, default='outcome', max_length=100),
        ),
        migrations.AlterField(
            model_name='goals',
            name='performance_goal_1',
            field=models.CharField(blank=True, default='performance goal', max_length=100),
        ),
        migrations.AlterField(
            model_name='goals',
            name='performance_goal_2',
            field=models.CharField(blank=True, default='performance goal', max_length=100),
        ),
        migrations.AlterField(
            model_name='goals',
            name='performance_goal_3',
            field=models.CharField(blank=True, default='performance goal', max_length=100),
        ),
        migrations.AlterField(
            model_name='goals',
            name='process_goal_1',
            field=models.CharField(blank=True, default='process goal', max_length=100),
        ),
        migrations.AlterField(
            model_name='goals',
            name='process_goal_2',
            field=models.CharField(blank=True, default='process goal', max_length=100),
        ),
        migrations.AlterField(
            model_name='goals',
            name='process_goal_3',
            field=models.CharField(blank=True, default='process goal', max_length=100),
        ),
        migrations.AlterField(
            model_name='goals',
            name='process_goal_4',
            field=models.CharField(blank=True, default='process goal', max_length=100),
        ),
    ]
