# Generated by Django 3.1.3 on 2021-02-08 16:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset', '0004_auto_20210125_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='can_control',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
        migrations.AlterField(
            model_name='control',
            name='cannot_control',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
