# Generated by Django 3.1.3 on 2021-03-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset', '0005_auto_20210208_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='title',
            field=models.CharField(blank=True, default='Title', max_length=100),
        ),
    ]
