# Generated by Django 3.1.3 on 2021-03-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset', '0006_goals_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='outcome',
            field=models.TextField(blank=True, default='outcome', max_length=256),
        ),
    ]
