# Generated by Django 3.1.3 on 2021-01-25 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horse', '0018_auto_20210117_1717'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0010_auto_20210121_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('lightbulb', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, default='', upload_to='media/images/competition')),
                ('notes', models.TextField(blank=True)),
                ('myStars', models.CharField(blank=True, max_length=100)),
                ('videoLink', models.CharField(blank=True, max_length=100)),
                ('disipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.customimages')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueName', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('refreshments', models.CharField(blank=True, max_length=100)),
                ('prizes', models.CharField(blank=True, max_length=100)),
                ('atmosphere', models.CharField(blank=True, max_length=100)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competing.competitionlog')),
            ],
        ),
        migrations.CreateModel(
            name='Comphorse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horseClass', models.CharField(blank=True, max_length=100)),
                ('performance', models.TextField(blank=True)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competing.competitionlog')),
                ('horse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horse.horse')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
