# Generated by Django 3.1.3 on 2021-01-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comphorse',
            name='class_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
