# Generated by Django 3.1.3 on 2021-01-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comphorse',
            old_name='cclass',
            new_name='horseClass',
        ),
        migrations.AddField(
            model_name='comphorse',
            name='performance',
            field=models.TextField(blank=True),
        ),
    ]
