# Generated by Django 3.1.3 on 2021-01-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competing', '0002_comphorse_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionlog',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
