# Generated by Django 3.1.3 on 2021-02-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competing', '0004_auto_20210131_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='atmosphere',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='venue',
            name='prizes',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='venue',
            name='refreshments',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='venue',
            name='value',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1),
        ),
    ]
