# Generated by Django 3.1.3 on 2021-02-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competing', '0005_auto_20210201_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='atmosphere',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='venue',
            name='prizes',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='venue',
            name='refreshments',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='venue',
            name='value',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
