# Generated by Django 3.1.3 on 2021-02-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competing', '0006_auto_20210202_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
