# Generated by Django 3.1.3 on 2021-03-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competing', '0008_auto_20210302_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comphorse',
            old_name='scores',
            new_name='performance',
        ),
    ]
