# Generated by Django 3.1.3 on 2022-08-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competing', '0010_auto_20210406_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comphorse',
            old_name='performance',
            new_name='cost',
        ),
    ]
