# Generated by Django 3.1.3 on 2022-09-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competing', '0012_auto_20220808_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionlog',
            name='disipline',
            field=models.CharField(blank=True, default='xc', max_length=100),
            preserve_default=False,
        ),
    ]
