# Generated by Django 3.1.3 on 2021-03-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0002_auto_20210313_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='pay_rate_currency',
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pay_rate',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
