# Generated by Django 3.1.3 on 2021-03-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0003_auto_20210314_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='termination_date',
            field=models.DateField(blank=True),
        ),
    ]
