# Generated by Django 3.1.3 on 2021-03-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0004_auto_20210314_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
