# Generated by Django 3.1.3 on 2021-04-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0005_auto_20210314_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
