# Generated by Django 3.1.3 on 2021-04-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0007_auto_20210407_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
