# Generated by Django 3.1.3 on 2022-07-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0009_auto_20210411_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
