# Generated by Django 3.1.3 on 2022-07-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0011_remove_staff_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
