# Generated by Django 3.1.3 on 2022-09-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0013_remove_staff_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='ni_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
