# Generated by Django 3.1.3 on 2023-03-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0015_client_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passport',
            field=models.ImageField(blank=True, default='media/images/clients/profile.png', upload_to='media/images/clients'),
        ),
    ]
