# Generated by Django 3.1.3 on 2021-01-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='report',
            field=models.ImageField(blank=True, upload_to='media/images/appoint'),
        ),
    ]
