# Generated by Django 3.1.3 on 2022-09-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_remove_appointment_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='report',
            field=models.FileField(upload_to='media/images/reports'),
        ),
    ]
