# Generated by Django 3.1.3 on 2023-03-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subId',
            field=models.CharField(default='Free', max_length=254),
        ),
    ]
