# Generated by Django 3.1.3 on 2023-03-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230324_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='periodEnd',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
