# Generated by Django 3.1.3 on 2023-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230324_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subId',
            field=models.CharField(default='', max_length=254),
        ),
    ]
