# Generated by Django 3.1.3 on 2023-03-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20230325_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subId',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
