# Generated by Django 3.1.3 on 2023-03-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230331_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subId',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
