# Generated by Django 3.1.3 on 2021-01-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_traininglog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='date',
            field=models.DateField(),
        ),
    ]
