# Generated by Django 3.1.3 on 2021-01-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20210120_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
