# Generated by Django 3.1.3 on 2021-01-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20210120_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='floorPlan',
            field=models.ImageField(blank=True, default='media/images/floor_plan.jpg', upload_to='media/images/floorplan'),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='notes',
            field=models.TextField(blank=True, default='Add some notes'),
        ),
    ]
