# Generated by Django 3.1.3 on 2021-01-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20210121_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='notes',
            field=models.TextField(default='Add some notes'),
        ),
    ]
