# Generated by Django 3.1.3 on 2021-01-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20210121_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
