# Generated by Django 3.1.3 on 2021-01-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20210121_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='files',
            field=models.FileField(blank=True, upload_to='media/uploads'),
        ),
    ]
