# Generated by Django 3.1.3 on 2021-01-21 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0018_auto_20210117_1717'),
        ('training', '0009_auto_20210121_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='horse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horse.horse'),
        ),
    ]
