# Generated by Django 3.1.3 on 2021-02-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20210121_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
