# Generated by Django 3.1.3 on 2021-03-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_auto_20210204_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disipline', models.CharField(blank=True, choices=[('Dressage', 'Dressage'), ('ShowJumping', 'ShowJumping'), ('Eventing', 'Eventing'), ('PonyClub', 'PonyClub')], default='Dressage', max_length=100)),
            ],
        ),
    ]
