# Generated by Django 3.1.3 on 2021-03-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_disipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disipline',
            name='disipline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
