# Generated by Django 3.1.3 on 2021-03-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_auto_20210308_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimages',
            name='disipline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
