# Generated by Django 3.1.3 on 2021-03-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_auto_20210308_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimages',
            name='image',
            field=models.ImageField(blank=True, default='media/images/200x300.png', upload_to='media/images/custom'),
        ),
    ]
