# Generated by Django 3.1.3 on 2022-09-05 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_auto_20210309_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='disipline',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
