# Generated by Django 3.1.3 on 2020-12-28 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showName', models.CharField(default='Show Name', max_length=100)),
                ('stableName', models.CharField(default='Stable Name', max_length=100)),
                ('photo', models.ImageField(blank=True, default='', upload_to='media/images/horses')),
                ('breed', models.CharField(default='Irish Cob', max_length=100)),
                ('Gender', models.CharField(choices=[('Gelding', 'Gelding'), ('Mare', 'Mare'), ('Stallion', 'Stallion')], default='Gelding', max_length=40)),
                ('pedigree', models.CharField(default='Sire/Dam', max_length=200)),
                ('height', models.DecimalField(decimal_places=1, max_digits=3)),
                ('markings', models.TextField()),
                ('Dob', models.DateField(auto_now_add=True)),
                ('owner', models.CharField(default='John Doe', max_length=100)),
                ('street_address1', models.CharField(blank=True, max_length=40)),
                ('street_address2', models.CharField(blank=True, max_length=40)),
                ('town_or_city', models.CharField(blank=True, max_length=40)),
                ('county', models.CharField(blank=True, max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('links', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
