# Generated by Django 3.1.3 on 2020-12-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='links',
        ),
        migrations.AddField(
            model_name='horse',
            name='usefulllinks',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
