# Generated by Django 3.1.3 on 2021-01-03 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horse', '0002_auto_20201228_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='height',
            field=models.DecimalField(decimal_places=1, default=15.3, max_digits=3),
        ),
        migrations.AlterField(
            model_name='horse',
            name='markings',
            field=models.TextField(default='patchy twat'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='pedigree',
            field=models.CharField(default='Sire x Dam', max_length=200),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=100, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
