# Generated by Django 3.1.3 on 2021-01-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0003_auto_20210103_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='usefulllinks',
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='organisation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
