# Generated by Django 3.1.3 on 2021-01-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0006_auto_20210108_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='horse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horse.horse'),
        ),
    ]
