# Generated by Django 3.1.3 on 2021-01-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0009_horse_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='passport',
            field=models.ImageField(blank=True, default='static/images/passport.jpg', upload_to='media/images/passport'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/horse.jpeg', upload_to='media/images/horses'),
        ),
    ]
