# Generated by Django 3.1.3 on 2021-01-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0011_auto_20210110_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='passport',
            field=models.ImageField(blank=True, default='/media/images/passport.jpg', upload_to='media/images/passport'),
        ),
    ]
