# Generated by Django 3.1.3 on 2021-01-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0012_auto_20210110_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='passport',
            field=models.ImageField(blank=True, default='media/images/passport.jpg', upload_to='media/images/passport'),
        ),
    ]
