# Generated by Django 3.1.3 on 2021-01-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0014_tack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='Dob',
            field=models.DateField(),
        ),
    ]
