# Generated by Django 3.1.3 on 2021-01-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0015_auto_20210117_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='feeds',
            field=models.TextField(blank=True, default='behaviour etc'),
        ),
    ]
