# Generated by Django 3.1.3 on 2021-04-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0021_auto_20210405_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horse',
            old_name='color',
            new_name='colour',
        ),
    ]
