# Generated by Django 3.1.3 on 2021-04-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0022_auto_20210405_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='horse',
            name='contact_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
