# Generated by Django 3.1.3 on 2021-04-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0023_auto_20210405_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='markings',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
