# Generated by Django 3.1.3 on 2021-04-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0024_horse_markings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='contact_mobile',
        ),
    ]
