# Generated by Django 3.1.3 on 2021-04-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0025_auto_20210405_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='markings',
        ),
    ]
