# Generated by Django 3.1.3 on 2021-04-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0026_remove_horse_markings'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='horse',
            name='owner_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
