# Generated by Django 3.1.3 on 2022-08-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0027_auto_20210406_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='chip',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
