# Generated by Django 3.1.3 on 2022-09-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0028_horse_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='colour',
            field=models.TextField(default='markings'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='photo',
            field=models.FileField(blank=True, default='media/images/horses/horse.jpeg', upload_to='media/images/horses'),
        ),
    ]
