# Generated by Django 3.1.3 on 2022-09-01 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0029_auto_20220901_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, default='media/images/horses/horse.jpeg', upload_to='media/images/horses')),
                ('horse', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='horse.horse')),
            ],
        ),
    ]
