# Generated by Django 3.1.3 on 2022-09-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0030_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='showName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='horse',
            name='stableName',
            field=models.CharField(max_length=100),
        ),
    ]
