# Generated by Django 3.1.3 on 2022-09-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0032_auto_20220916_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
