# Generated by Django 3.1.3 on 2022-09-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0033_auto_20220916_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='Arrived',
            field=models.DateField(default='2015-01-01'),
        ),
        migrations.AddField(
            model_name='horse',
            name='Left',
            field=models.DateField(default='2015-01-01'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='colour',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='horse',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='horse',
            name='owner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='horse',
            name='pedigree',
            field=models.CharField(max_length=200),
        ),
    ]
