# Generated by Django 3.1.3 on 2022-10-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0036_auto_20221010_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='Arrived',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='Dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='Left',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='colour',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
