# Generated by Django 3.1.3 on 2022-11-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0037_auto_20221010_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images_P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, default='media/images/passport.jpg', upload_to='media/images/passport')),
                ('horse', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='horse.horse')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
