# Generated by Django 3.1.3 on 2023-03-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0038_auto_20221104_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='photo',
            field=models.FileField(blank=True, default='media/images/horses/horse.png', upload_to='media/images/horses'),
        ),
    ]
